FROM python:3.7-buster

RUN apt-get update && apt-get install -y \
    apt-utils \
    libsasl2-dev \
    python3-dev \
    libldap2-dev \
    libssl-dev \
    default-libmysqlclient-dev \
    sqlite3

RUN pip3 install django==3.1.2 psycopg2-binary==2.9.1 django-auth-ldap==3.0.0 gunicorn==20.1.0 requests==2.22.0 BeautifulSoup4==4.10.0 mysqlclient==2.0.3 boto3==1.18.58

