apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressionapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressionapp
  template:
    metadata:
      labels:
        app: expressionapp
    spec:
      serviceAccount: secretsmanager
      containers:
      - name: expressionapp
        image: lab1expressionapp_image
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1000m
            memory: 2048Mi
        env:
          - name: --env
            value: "DEV"
        ports:
        - containerPort: 3838
          name: expressionapp
---

apiVersion: v1
kind: Service
metadata:
  name: expressionapp
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ports:
  - port: 80
    targetPort: 3838
    protocol: TCP
  type: NodePort
  selector:
    app: expressionapp

