apiVersion: apps/v1
kind: Deployment
metadata:
  name: sciview
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sciview
  template:
    metadata:
      labels:
        app: sciview
    spec:
      serviceAccount: secretsmanager
      containers:
      - name: sciview
        image: sciview_image
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2000m
            memory: 4096Mi
        ports:
        - containerPort: 3838
          name: sciview
---

apiVersion: v1
kind: Service
metadata:
  name: sciview
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ports:
  - port: 80
    targetPort: 3838
    protocol: TCP
  type: NodePort
  selector:
    app: sciview



